CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) UNIQUE NOT NULL,
  login varchar(50) UNIQUE NOT NULL,
  name varchar(100),
  birthday date NOT NULL
);